### ISSUE TITLE
CSS missing from coverage reports?

### ISSUE THREAD

**Issue by yamikuronue** [CrocInc/grunt-croc-qunit#1]
This super weird, but using the following config:

```
coverageInstrument: {
      test: {
        src: '**/js/**/*.js',
        expand: true,
        cwd: '../webroot/assets',
        dest: 'webroot/assets'
      }
    },
    coverageReport: {
      test: {
        options: {
          reports: {
            html: 'reports/coverage'
          }
        }
      }
    }
```

from inside a build folder (where my source code is in webroot, and my gruntfile is in build, and they share a parent), the resulting html files can't seem to find their CSS.

The top level report looks fine, but when I click on the report for any given file, it's looking for `build/reports/prettify.css` instead of `build/reports/coverage/prettify.css`

Am I doing something wrong here?

**Comment by evil-shrike** [comment]
I'm not sure that I understand your configuration. But this looks suspicious:  `dest: 'webroot/assets'`
Usually `dest` is a temp folder.
Please take a look into the [sample](https://github.com/CrocInc/grunt-croc-qunit/blob/master/example/grunt-croc-qunit-sample/Gruntfile.js#L63).
Can you reproduce issue in it?

**Comment by yamikuronue** [comment]
Yeah, sorry, what I'm having it do is create a temporary webroot inside my test directory, but I'm sure it's really confusing to read :)

I'll check this afternoon if I can reproduce

**Comment by yamikuronue** [comment]
I think it has to do with the fact I'm not running from the root of the project.

When I create a subfolder inside the sample configuration, copy the gruntfile and the package.json into it, and modify the gruntfile to use the subfolder, I get one of the stylesheets referring to a nonexistant file:

`file:///C:/Users/yamikuronue/Documents/GitHub/grunt-croc-qunit/example/grunt-croc-qunit-sample/subfolder/.tmp/coverageReports/src/prettify.css`

The file is actually at `C:\Users\yamikuronue\Documents\GitHub\grunt-croc-qunit\example\grunt-croc-qunit-sample\subfolder\.tmp\coverageReports\html\prettify.css`

The page doesn't look as broken, but that's one symptom reproduced. Here's the config changes I had to make to support running from a subfolder:

```
connect: {
            testserver: {
                options: {
                    port: 9001,
                    hostname: '127.0.0.1',
                    middleware: function (connect) {
                        return [
                            mountFolder(connect, '../src'),
                            mountFolder(connect, '../tests'),
                        ];
                    }
                }
            },
            test: {
                options: {
                    port: 9002,
                    hostname: '127.0.0.1',
                    middleware: function (connect) {
                        return [
                            mountFolder(connect, '../src'),
                            mountFolder(connect, '../tests'),
                        ];
                    }
                }
            },
            testcoverage: {
                options: {
                    port: 9002,
                    hostname: '127.0.0.1',
                    middleware: function (connect) {
                        return [
                            mountFolder(connect, '.tmp'),
                            mountFolder(connect, '../src'),
                            mountFolder(connect, '../tests'),
                        ]
                    }
                }
            }
        },
        coverageInstrument: {
            test: {
                src: 'lib/**/*.js',
                expand: true,
                cwd: '../src',
                dest: '.tmp'
            }
        },
        coverageReport: {
            test: {
                options: {
                    reports: {
                        html: '.tmp/coverageReports/html/'
                    }               
                }
            }
        }
    });
```

**Comment by yamikuronue** [comment]
Yep, modifying my gruntfile to run from the root of my project resovles the issue. So either 
1. Running from a subfolder is not supported, or
2. Running from a subfolder is supported but there's a bug :)

**Comment by evil-shrike** [comment]
I think putting `Gruntfile.js` inside a subfolder isn't correct. It should in the project root dir along with `package.json`.
coverageReport's reports folder and coverageInstrument's dest folder could be in any place (above or below).
So if you don't mind I'll close the issue. Feel free to reopen if you have any other thought. Thanks.
