### ISSUE TITLE
Force flag?

### ISSUE THREAD

**Issue by yamikuronue** [CrocInc/grunt-croc-qunit#6]
grunt-contrib-qunit has a "force:true" option that doesn't fail the task if your tests fail. Is there such a thing in this module, and if not, can there be? When gathering coverage metrics I usually want to go on and see what coverage was obtained even while the test fails, as it can help in debugging. For the time being I can use grunt's --force flag, but I'd like to still fail if other tasks fail if possible.

**Comment by evil-shrike** [comment]
Hi @yamikuronue I can check this next week, if you ping a comment here - it'd nice

**Comment by evil-shrike** [comment]
`force` option is Implemented in 0.4.0

**Comment by yamikuronue** [comment]
Oh, thank you! Sorry I forgot to ping you :)
